### ISSUE TITLE
Unit for barometer is wrong (hPA instead of hPa) (rev. 13)

### ISSUE THREAD

**Issue by simon-budig** [spacedirectory/schema#2]
The unit for the "barometer" device is wrongly capitalized, it should be "hPa" instead of "hPA" (see https://en.wikipedia.org/wiki/Pascal_%28unit%29 )

**Comment by dbrgn** [comment]
You're obviously right.

@rnestler @dns2utf8 @rorist would this be a breaking change in an already published spec if we change the capitalization of one of multiple valid values? Does this need to go into the v14 draft?

**Comment by dbrgn** [comment]
I just crawled the entire directory. Right now a single space is providing barometer data:

https://hskrk-spacemon.herokuapp.com/

**Comment by rorist** [comment]
Hi, maybe we could simplify the sensors. Because now it's almost always an array of objet with value, unit, location, and desc. We could write the specs so its' backward compatible with the detailed sensors, and remove them all, so people can add their own sensors. And still provide examples of sensors.

**Comment by dbrgn** [comment]
Hm, I think some of the sensors should be standardized, e.g. people now present.

But simplification might be an option.

**Comment by simon-budig** [comment]
I have no clue how the specification is handled.

For v13 it might be an option to just add "hPa" as enum value in addition to "hPA", and then drop "hPA" in v14. That way it is possible for hackspaces (our hackspace in Siegen actually provides a barometric value of "null" - grgh) to deliver the sensor value correctly without breaking the other hackspaces.

**Comment by dns2utf8** [comment]
I think it would be a breaking change.
But since it would only apply to two spaces, we could also change both endpoints.

What do you think @HackerspaceKRK @simon-budig ?

**Comment by dbrgn** [comment]
We don't know whether there are other applications that will consider `hPa` as invalid. It should be according to the published spec, after all. Since it doesn't hurt anyone, I'd actually stick with the wrong writing and fix it in v0.14.

See https://github.com/spacedirectory/schema/pull/3 for v0.14 discussion.

@simon-budig what do you think? :)

**Comment by dns2utf8** [comment]
WORKS FOR ME

**Comment by dns2utf8** [comment]
This issues is about to be resolved in #7. Please comment there.
